version: '0.6.0.{build}'
image: Visual Studio 2022
environment:
  nodejs_version: "12"
branches:
  only:
  - master
  - develop
init:
  - cmd: git config --global core.autocrlf true
install:
  - ps: Install-Product node $env:nodejs_version
before_build:
  - cmd: dotnet --version
  - cmd: node --version
  - cmd: npm --version
build_script:
  - cmd: dotnet build ./Content/Vue.Simple.Template.sln -v quiet
after_build:
  - cmd: dotnet pack Vue.Simple.Project.Template.csproj -v quiet
artifacts:
  - path: '**/*.nupkg'
skip_commits:
  files:
    - '**/*.md'
deploy:
- provider: NuGet
  server: https://www.myget.org/F/vue-simple-template/api/v2/package
  on:
    branch: develop
  api_key:
    secure: 6xhHSsDvB9arsrSDLuynnbxaVS+BwaoJU96RfQenc5FOnUYvP8SHM6kbvrmpvja2
  skip_symbols: false
